from typing import Dict, Any, Optional

from models.content import (
    ContentType,
    Industry,
    City,
    Language,
    Tone,
)


def format_content_for_export(
    content: str,
    metadata: Dict[str, Any],
    fmt: str = "markdown",
) -> str:
    if fmt == "markdown":
        return _format_as_markdown(content, metadata)
    elif fmt == "html":
        return _format_as_html(content, metadata)
    elif fmt == "plain":
        return _format_as_plain(content, metadata)
    return content


def _format_as_markdown(content: str, metadata: Dict[str, Any]) -> str:
    lines = []
    lines.append(f"# {metadata.get('business_name', 'Content')}")
    lines.append("")
    if metadata.get("content_type"):
        lines.append(f"**Type:** {metadata['content_type']}")
    if metadata.get("industry"):
        lines.append(f"**Industry:** {metadata['industry']}")
    if metadata.get("city"):
        lines.append(f"**City:** {metadata['city']}")
    if metadata.get("language"):
        lines.append(f"**Language:** {metadata['language']}")
    if metadata.get("tone"):
        lines.append(f"**Tone:** {metadata['tone']}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(content)
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by ContentPK AI on {metadata.get('timestamp', '')}*")
    return "\n".join(lines)


def _format_as_html(content: str, metadata: Dict[str, Any]) -> str:
    meta_html = ""
    for key in ["business_name", "content_type", "industry", "city", "language", "tone"]:
        if metadata.get(key):
            meta_html += f"<p><strong>{key.replace('_', ' ').title()}:</strong> {metadata[key]}</p>\n"
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{metadata.get("business_name", "Content")}</title></head>
<body>
{meta_html}
<hr>
{content.replace(chr(10), "<br>")}
<hr>
<p><em>Generated by ContentPK AI on {metadata.get("timestamp", "")}</em></p>
</body>
</html>"""


def _format_as_plain(content: str, metadata: Dict[str, Any]) -> str:
    lines = [f"Title: {metadata.get('business_name', 'Content')}"]
    if metadata.get("content_type"):
        lines.append(f"Type: {metadata['content_type']}")
    lines.append("")
    lines.append(content)
    return "\n".join(lines)


def calculate_trend(current: int, previous: int) -> Optional[str]:
    """Calculate percentage trend between two periods.

    Returns:
        "+N%" if positive change
        "-N%" if negative change
        "0%" if no change
        "+New" if previous is 0 and current > 0
        None if both are 0 (no data)
    """
    if current == 0 and previous == 0:
        return None
    if previous == 0:
        return "+New"
    if current == previous:
        return "0%"

    change = ((current - previous) / previous) * 100
    if change > 0:
        return f"+{change:.1f}%"
    else:
        return f"{change:.1f}%"  # Python already includes the minus sign


CONTENT_TYPE_LABELS = {
    ContentType.SOCIAL_MEDIA: {
        "en": "Social Media Post",
        "ur": "سوشل میڈیا پوسٹ",
    },
    ContentType.BLOG_ARTICLE: {
        "en": "Blog Article",
        "ur": "بلاگ آرٹیکل",
    },
    ContentType.PRODUCT_DESCRIPTION: {
        "en": "Product Description",
        "ur": "مصنوعات کی تفصیل",
    },
    ContentType.EMAIL_MARKETING: {
        "en": "Email Marketing",
        "ur": "ای میل مارکیٹنگ",
    },
    ContentType.PRESS_RELEASE: {
        "en": "Press Release",
        "ur": "پریس ریلیز",
    },
    ContentType.WEBSITE_CONTENT: {
        "en": "Website Content",
        "ur": "ویب سائٹ کا مواد",
    },
    ContentType.ADVERTISEMENT_COPY: {
        "en": "Advertisement Copy",
        "ur": "اشتہاری کاپی",
    },
}

INDUSTRY_LABELS = {
    Industry.TEXTILE: {"en": "Textile", "ur": "ٹیکسٹائل"},
    Industry.IT_SOFTWARE: {"en": "IT & Software", "ur": "آئی ٹی اور سافٹ ویئر"},
    Industry.AGRICULTURE: {"en": "Agriculture", "ur": "زراعت"},
    Industry.MANUFACTURING: {"en": "Manufacturing", "ur": "مینوفیکچرنگ"},
    Industry.ECOMMERCE: {"en": "E-Commerce", "ur": "ای کامرس"},
    Industry.REAL_ESTATE: {"en": "Real Estate", "ur": "رئیل اسٹیٹ"},
    Industry.FOOD_BEVERAGE: {"en": "Food & Beverage", "ur": "خوراک اور مشروبات"},
    Industry.HEALTHCARE: {"en": "Healthcare", "ur": "صحت کی دیکھ بھال"},
    Industry.EDUCATION: {"en": "Education", "ur": "تعلیم"},
    Industry.LOGISTICS: {"en": "Logistics", "ur": "لاجسٹکس"},
}

CITY_LABELS = {
    City.KARACHI: {"en": "Karachi", "ur": "کراچی"},
    City.LAHORE: {"en": "Lahore", "ur": "لاہور"},
    City.ISLAMABAD: {"en": "Islamabad", "ur": "اسلام آباد"},
    City.RAWALPINDI: {"en": "Rawalpindi", "ur": "راولپنڈی"},
    City.FAISALABAD: {"en": "Faisalabad", "ur": "فیصل آباد"},
    City.MULTAN: {"en": "Multan", "ur": "ملتان"},
    City.PESHAWAR: {"en": "Peshawar", "ur": "پشاور"},
    City.QUETTA: {"en": "Quetta", "ur": "کوئٹہ"},
    City.SIALKOT: {"en": "Sialkot", "ur": "سیالکوٹ"},
    City.GUJRANWALA: {"en": "Gujranwala", "ur": "گوجرانوالہ"},
}


def get_labels() -> Dict[str, Any]:
    return {
        "content_types": [
            {"value": ct.value, **CONTENT_TYPE_LABELS[ct]}
            for ct in ContentType
        ],
        "industries": [
            {"value": ind.value, **INDUSTRY_LABELS[ind]}
            for ind in Industry
        ],
        "cities": [
            {"value": city.value, **CITY_LABELS[city]}
            for city in City
        ],
        "languages": [
            {"value": lang.value, "en": lang.value.title(), "ur": "اردو" if lang.value == "urdu" else "رومن اردو" if lang.value == "roman_urdu" else "انگریزی"}
            for lang in Language
        ],
        "tones": [
            {"value": tone.value, "en": tone.value.title(), "ur": {
                Tone.PROFESSIONAL: "پیشہ ورانہ",
                Tone.CASUAL: "عام",
                Tone.PERSUASIVE: "قائل کرنے والا",
                Tone.INFORMATIVE: "معلوماتی",
                Tone.FRIENDLY: "دوستانہ",
            }[tone]}
            for tone in Tone
        ],
    }
